---
version: '3.8'

services:
  runner:
    image: docker-github-runner-lin:latest
    build:
      context: .
      args:
        RUNNER_VERSION: '2.292.0'
    environment:
      GH_TOKEN: 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
      GH_OWNER: selsiofy
      GH_REPOSITORY: DockerRunner
